# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

all:
  aloha:
    defaultPlugins:
      - common/format
      - common/list
      - common/link
      - common/highlighteditables
      - common/block
      - common/undo
      - common/contenthandler
      - common/paste
      - common/commands
      - common/table
      - common/align
      - sfAloha/save
      - sfAloha/image-upload

    # Tells whether new content can be automatically created or not
    autoAdd:                              true

    image_upload_dir:                     aloha-images
    backend:                              sfAlohaBackendDoctrine

    security:
      edit:
        # Tells whether only authenticated users can edit content or not
        authenticated:                    true

        # Tells whether only users with the given credential(s) can edit content or not
        # ~ for no specific credentials, a table for several allowed credentials (e.g. [admin, writer]), string for only one
        credentials:                      ~
