# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

aloha_content_save:
  url:   /aloha/content/save
  param: { module: sfAlohaContent, action: save }

aloha_upload_file:
  url:   /cms/upload-file
  param: { module: sfAlohaContent, action: uploadFile  }
