options:
  collate: utf8_unicode_ci
  charset: utf8

AlohaContent:
  actAs:
    - Timestampable
    - Versionable
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
      unsigned: true
      notnull: true
    name:
      type: string(255)
      notnull: true
    body:
      type: string(65535)
      notnull: true
  indexes:
    name_index:
      fields: [name]

